#!/usr/bin/env python
"""
Visionary RAG - REAL LLM-as-Judge Test
NO MOCKS - Actual Ollama API calls with real evaluation
"""

import requests
import json
from pathlib import Path
from datetime import datetime

def call_ollama_judge(query: str, answer: str, context: str, model: str = "llama3.2:3b"):
    """
    REAL LLM Judge - calls actual Ollama API
    Returns real scores, not mocked values
    """
    print(f"\n  Query: {query[:60]}...")
    print(f"  Answer: {answer[:80]}...")
    
    prompt = f"""You are an expert judge evaluating RAG system outputs.

QUERY: {query}

CONTEXT PROVIDED TO MODEL:
{context[:800]}

ANSWER GENERATED BY MODEL:
{answer}

Evaluate on these criteria:

1. HALLUCINATION: Does the answer contain information NOT in the context?
   Answer YES or NO only

2. COMPLETENESS: Does the answer fully address the query?
   Rate 0.0 to 1.0 (0 = incomplete, 1 = fully complete)

3. CLARITY: Is the answer clear and well-structured?
   Rate 0.0 to 1.0 (0 = confusing, 1 = very clear)

4. OVERALL QUALITY: Considering all factors
   Rate 0.0 to 1.0

Respond in this EXACT format:
HALLUCINATION: YES or NO
COMPLETENESS: [number 0.0-1.0]
CLARITY: [number 0.0-1.0]
OVERALL: [number 0.0-1.0]
FEEDBACK: [one sentence explanation]"""

    try:
        response = requests.post(
            "http://localhost:11434/api/generate",
            json={
                "model": model,
                "prompt": prompt,
                "stream": False
            },
            timeout=60
        )
        
        if response.status_code == 200:
            judgment = response.json().get("response", "")
            print(f"  Judge Response:\n{judgment[:300]}...")
            
            # Parse the judgment
            result = {
                "query": query,
                "answer": answer[:200],
                "context_length": len(context),
                "hallucination_detected": "YES" in judgment.upper().split("HALLUCINATION:")[1].split("\n")[0] if "HALLUCINATION:" in judgment.upper() else False,
                "completeness_score": 0.0,
                "clarity_score": 0.0,
                "judge_score": 0.0,
                "judge_feedback": ""
            }
            
            # Extract scores
            for line in judgment.split('\n'):
                line = line.strip().upper()
                if "COMPLETENESS:" in line:
                    try:
                        score = float(line.split(":")[1].strip().replace(',', '.'))
                        result["completeness_score"] = score
                    except:
                        pass
                elif "CLARITY:" in line:
                    try:
                        score = float(line.split(":")[1].strip().replace(',', '.'))
                        result["clarity_score"] = score
                    except:
                        pass
                elif "OVERALL:" in line:
                    try:
                        score = float(line.split(":")[1].strip().replace(',', '.'))
                        result["judge_score"] = score
                    except:
                        pass
                elif "FEEDBACK:" in line:
                    result["judge_feedback"] = line.split(":", 1)[1].strip()
            
            return result
        else:
            print(f"  ❌ API Error: {response.status_code}")
            return None
            
    except Exception as e:
        print(f"  ❌ Error: {e}")
        return None

def run_real_judge_test():
    """Run REAL LLM Judge test with actual data."""
    print("\n" + "="*70)
    print("REAL LLM-AS-JUDGE TEST - NO MOCKS")
    print("="*70)
    
    # Check if Ollama is running
    try:
        response = requests.get("http://localhost:11434/api/tags", timeout=5)
        if response.status_code == 200:
            models = response.json().get("models", [])
            print(f"\n✅ Ollama running with {len(models)} models:")
            for m in models:
                print(f"   - {m['name']}")
        else:
            print("❌ Ollama not responding")
            return
    except Exception as e:
        print(f"❌ Cannot connect to Ollama: {e}")
        return
    
    # REAL test cases from actual RAG output
    test_cases = [
        {
            "query": "What is photosynthesis?",
            "answer": "Photosynthesis is the process by which green plants and some other organisms use sunlight to synthesize foods with the help of chlorophyll. Photosynthesis converts carbon dioxide and water into glucose and oxygen.",
            "context": "Photosynthesis occurs in chloroplasts which contain chlorophyll. Plants use sunlight energy to convert CO2 and H2O into glucose (C6H12O6) and release oxygen as a byproduct. The overall equation is: 6CO2 + 6H2O + light energy → C6H12O6 + 6O2. This process is essential for life on Earth as it provides food and oxygen."
        },
        {
            "query": "What is force in physics?",
            "answer": "In physics, a force is any interaction that, when unopposed, will change the motion of an object. Force can be described as a push or pull. It is a vector quantity with both magnitude and direction. The SI unit of force is the newton (N).",
            "context": "In physics, a force is any interaction that, when unopposed, will change the motion of an object. Force can be described as a push or pull. It is a vector quantity with both magnitude and direction. The SI unit of force is the newton (N). Forces can cause objects to accelerate, decelerate, remain in place, or deform."
        },
        {
            "query": "What are microorganisms?",
            "answer": "Microorganisms are microscopic living organisms that are too small to be seen with the naked eye. They include bacteria, viruses, fungi, protozoa, and algae. Microorganisms can be found everywhere - in air, water, soil, and inside living bodies.",
            "context": "Microorganisms are unicellular or multicellular living organisms that are too small to be seen without a microscope. They include bacteria (single-celled prokaryotes), viruses (non-cellular infectious agents), fungi (can be unicellular like yeast or multicellular like molds), protozoa (single-celled eukaryotes), and some algae. Microorganisms are found in every habitat on Earth."
        }
    ]
    
    print(f"\n📊 Evaluating {len(test_cases)} test cases with REAL LLM Judge...\n")
    
    results = []
    
    for i, case in enumerate(test_cases, 1):
        print(f"[{i}/{len(test_cases)}] Evaluating...")
        result = call_ollama_judge(
            query=case["query"],
            answer=case["answer"],
            context=case["context"]
        )
        
        if result:
            results.append(result)
            print(f"\n  📈 Scores:")
            print(f"     Hallucination: {result['hallucination_detected']}")
            print(f"     Completeness: {result['completeness_score']:.2f}")
            print(f"     Clarity: {result['clarity_score']:.2f}")
            print(f"     Overall: {result['judge_score']:.2f}")
            print(f"     Feedback: {result['judge_feedback']}")
    
    # Calculate aggregate metrics
    if results:
        avg_completeness = sum(r["completeness_score"] for r in results) / len(results)
        avg_clarity = sum(r["clarity_score"] for r in results) / len(results)
        avg_judge = sum(r["judge_score"] for r in results) / len(results)
        hallucination_rate = sum(1 for r in results if r["hallucination_detected"]) / len(results)
        
        print("\n" + "="*70)
        print("REAL LLM JUDGE RESULTS - AGGREGATE")
        print("="*70)
        print(f"\n  Test Cases Evaluated: {len(results)}")
        print(f"  Average Completeness: {avg_completeness:.3f}")
        print(f"  Average Clarity: {avg_clarity:.3f}")
        print(f"  Average Judge Score: {avg_judge:.3f}")
        print(f"  Hallucination Rate: {hallucination_rate:.1%}")
        
        # Save results
        output = {
            "test_date": datetime.now().isoformat(),
            "model": "llama3.2:3b",
            "test_cases": len(results),
            "results": results,
            "aggregate": {
                "avg_completeness": round(avg_completeness, 3),
                "avg_clarity": round(avg_clarity, 3),
                "avg_judge_score": round(avg_judge, 3),
                "hallucination_rate": round(hallucination_rate, 3)
            },
            "note": "REAL RESULTS - No mocks, actual Ollama API calls"
        }
        
        output_path = Path("data/REAL_llm_judge_results.json")
        with open(output_path, 'w') as f:
            json.dump(output, f, indent=2)
        
        print(f"\n✅ REAL results saved to: {output_path}")
        print("="*70)
        
        return output
    else:
        print("\n❌ No results obtained")
        return None

if __name__ == "__main__":
    run_real_judge_test()
